### ISSUE TITLE
Changing style for items

### ISSUE THREAD

**Issue by markosole** [Cobinja/cobi-flutter-settings#1]
Thanks for great plugin. I am using Dark theme for my app and was quiet difficult to setup colors. I would suggest feature for passing custom colors.

In example below, I had to change Group label color to white54 and I could not do it by setting just default accentColor which is different overall. 

## settings_group.dart

    return Container(
        child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          textAlign: TextAlign.left,
          overflow: TextOverflow.fade,
          style: TextStyle(
            // color: Theme.of(context).accentColor,
            color: Colors.white54,
          ),
        ),
        ...content,
      ],
    ));

**Comment by Cobinja** [comment]
Done with https://github.com/Cobinja/cobi-flutter-settings/commit/ce86857dcd0100384b4a0ba5d0d7162c01c774f3

**Comment by markosole** [comment]
Thanks 😊
